on: 
  workflow_dispatch:
  
jobs:
deploy:
  name: Releasing Legacy SDK iOS
  runs-on: macOS-latest
  steps:
    - name: Checkout merci-app/mcikit-podspec
      uses: actions/checkout@v3
      with:
        repository: merci-app/mcikit-podspec
        ref: version/2.0.0
